# Generated by Django 5.2 on 2025-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mesa',
            options={},
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='mesa',
            name='data_ocupacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponivel', max_length=10),
        ),
    ]
