# Generated by Django 5.2 on 2025-05-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_produtos_produto_id'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField()),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='id_cliente',
        ),
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.produtos'),
        ),
        migrations.AlterModelTable(
            name='pedidoitem',
            table='pedidos_itens',
        ),
        migrations.RenameModel(
            old_name='Pedidos_itens',
            new_name='PedidoItem',
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
